spring:
  data:
    mongodb:
      uri: mongodb://user:password@localhost:27017/miniautorizador?authSource=admin
      database: miniautorizador
      username: user
      password: password

authentication:
  basic:
    user: vrbeneficio
    password: password